[package]
name = "rs_vs_py_processing"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1.13.0"
rand = "0.8.5"
colored = "2.0.0"
polars = { version = "0.46.0", features = ["csv", "lazy", "parquet"] }
rayon = "1.8"
arrow = "5.0"
arrow2 = "0.17.4"
handle = "1.0.2"
